# Generated by Django 3.0.4 on 2020-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200401_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplete',
            new_name='datecompleted',
        ),
    ]
